#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ts=4 sts=4 sw=4 et:
"""
@author: Wu Liang
@authors: 
@date: Jun 4, 2012 8:24:36 PM
@contact: wuliang@maimiaotech.com
@version: 0.0.0
@deprecated:
@license:
@copyright:
"""

from Sku import Sku
from ConsignResult import ConsignResult
from SimbaItem import SimbaItem
from StaffEvalStatById import StaffEvalStatById
from FavoriteItem import FavoriteItem
from EvalDetail import EvalDetail
from Demographic import Demographic
from LogisticsVas import LogisticsVas
from ProductSpec import ProductSpec
from LimitDiscountDetail import LimitDiscountDetail
from AddressResult import AddressResult
from Department import Department
from RouteStatisticsInfo import RouteStatisticsInfo
from INWordCategory import INWordCategory
from ADGroupCatMatchPage import ADGroupCatMatchPage
from Brand import Brand
from AreaOption import AreaOption
from ProductImg import ProductImg
from CampaignSchedule import CampaignSchedule
from CatBrandSaleProp import CatBrandSaleProp
from LoginLog import LoginLog
from RouteCarriageInfo import RouteCarriageInfo
from SimbaItemPartition import SimbaItemPartition
from Duty import Duty
from ArticleSub import ArticleSub
from Task import Task
from Keyword import Keyword
from SubUserPermission import SubUserPermission
from IdsModule import IdsModule
from RouteAlpPage import RouteAlpPage
from Shipping import Shipping
from DiscountDetail import DiscountDetail
from Receiver import Receiver
from CreativeRecord import CreativeRecord
from FenxiaoPdu import FenxiaoPdu
from Shop import Shop
from ADGroupCatmatch import ADGroupCatmatch
from CouponDetail import CouponDetail
from Campaign import Campaign
from RouteVasInfo import RouteVasInfo
from Qscore import Qscore
from WangwangInfo import WangwangInfo
from PaimaiInfo import PaimaiInfo
from Distributor import Distributor
from ComplexLogisticsRoute import ComplexLogisticsRoute
from NotifyRefund import NotifyRefund
from Area import Area
from CarriageDetail import CarriageDetail
from StreamWeight import StreamWeight
from ItemProp import ItemProp
from INWordBase import INWordBase
from PurchaseOrder import PurchaseOrder
from UserCredit import UserCredit
from Location import Location
from Cooperation import Cooperation
from OnlineTimeById import OnlineTimeById
from PropImg import PropImg
from Picture import Picture
from ADGroup import ADGroup
from DeliveryTemplate import DeliveryTemplate
from Permission import Permission
from SubPurchaseOrder import SubPurchaseOrder
from ProductPropImg import ProductPropImg
from KfcSearchResult import KfcSearchResult
from SubUserFullInfo import SubUserFullInfo
from GroupMember import GroupMember
from ReplyStatOnDay import ReplyStatOnDay
from INCategoryAnalysis import INCategoryAnalysis
from OrderCharge import OrderCharge
from CampaignArea import CampaignArea
from RefundRemindTimeout import RefundRemindTimeout
from Subscription import Subscription
from PartnerDetail import PartnerDetail
from INCategoryBase import INCategoryBase
from SellerCat import SellerCat
from BrandCatControlInfo import BrandCatControlInfo
from RouteExtenalInfo import RouteExtenalInfo
from CancelOrderResult import CancelOrderResult
from Requisition import Requisition
from Place import Place
from LogisticsCompany import LogisticsCompany
from AfterSale import AfterSale
from SubAccountInfo import SubAccountInfo
from RecommendWord import RecommendWord
from KeywordPage import KeywordPage
from Item import Item
from TransitStepInfo import TransitStepInfo
from SubUserInfo import SubUserInfo
from Trade import Trade
from KeywordQscore import KeywordQscore
from RankedItem import RankedItem
from LogisticsVasCharge import LogisticsVasCharge
from UserInfo import UserInfo
from RecommendWordPage import RecommendWordPage
from OrderAmount import OrderAmount
from ScItem import ScItem
from ReplyStatById import ReplyStatById
from PromotionDisplayTop import PromotionDisplayTop
from ScItemMap import ScItemMap
from AppCustomer import AppCustomer
from InventorySum import InventorySum
from WaitingTimesOnDay import WaitingTimesOnDay
from INCategoryChildTop import INCategoryChildTop
from DeliveryTime import DeliveryTime
from Promotion import Promotion
from Meal import Meal
from Activity import Activity
from Creative import Creative
from NotifyTrade import NotifyTrade
from QueryRouteResult import QueryRouteResult
from Evaluation import Evaluation
from ArticleUserSubscribe import ArticleUserSubscribe
from Store import Store
from CompanyRouteSummary import CompanyRouteSummary
from ArticleBizOrder import ArticleBizOrder
from ADGroupPlace import ADGroupPlace
from FenxiaoSku import FenxiaoSku
from FavoriteShop import FavoriteShop
from ADGroupPage import ADGroupPage
from ExtraAttributes import ExtraAttributes
from StaffEvalStatOnDay import StaffEvalStatOnDay
from FreightCompany import FreightCompany
from Discount import Discount
from Subtask import Subtask
from INCategoryTop import INCategoryTop
from TopFee import TopFee
from ShopCat import ShopCat
from DemographicSetting import DemographicSetting
from OnlineTimesOnDay import OnlineTimesOnDay
from TradeRate import TradeRate
from User import User
from KeywordForecast import KeywordForecast
from CampaignPlatform import CampaignPlatform
from PromotionInItem import PromotionInItem
from LimitDiscount import LimitDiscount
from DiscardInfo import DiscardInfo
from Feature import Feature
from ADGroupCatMatchForecast import ADGroupCatMatchForecast
from INWordAnalysis import INWordAnalysis
from INCategoryProperties import INCategoryProperties
from RoutePromotionInfo import RoutePromotionInfo
from BrandCatControl import BrandCatControl
from Refund import Refund
from ReferenceDetail import ReferenceDetail
from Coupon import Coupon
from SubwayItem import SubwayItem
from SellerAuthorize import SellerAuthorize
from CreativePage import CreativePage
from PromotionInShop import PromotionInShop
from QueryPagination import QueryPagination
from Video import Video
from PicUrl import PicUrl
from FenxiaoGrade import FenxiaoGrade
from FenxiaoProduct import FenxiaoProduct
from TradeAmount import TradeAmount
from InventoryAuthorizeInfo import InventoryAuthorizeInfo
from LogisticsPartner import LogisticsPartner
from ItemCat import ItemCat
from ItemImg import ItemImg
from ItemTemplate import ItemTemplate
from NotifyItem import NotifyItem
from RefundMessage import RefundMessage
from ChannelOption import ChannelOption
from PictureCategory import PictureCategory
from Product import Product
from LogisticsVasItemCharge import LogisticsVasItemCharge
from CertPicInfo import CertPicInfo
from WaitingTimeById import WaitingTimeById
from PromotionDetail import PromotionDetail
from FoodSecurity import FoodSecurity
from ServiceOrder import ServiceOrder
from Role import Role
from LocalityLife import LocalityLife
from NonreplyStatById import NonreplyStatById
from TipInfo import TipInfo
from FenxiaoItemRecord import FenxiaoItemRecord
from ProductCat import ProductCat
from PropValue import PropValue
from CampaignBudget import CampaignBudget
from Order import Order
from NonReplyStatOnDay import NonReplyStatOnDay
from LoginUser import LoginUser
from TransportCharge import TransportCharge
from INRecordBase import INRecordBase
from UserTag import UserTag
from ShopScore import ShopScore
from TradeConfirmFee import TradeConfirmFee
from SubwayItemPartition import SubwayItemPartition
from DescModuleInfo import DescModuleInfo
from TradeMonitor import TradeMonitor
from GradeDiscount import GradeDiscount
