#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ts=4 sts=4 sw=4 et:
"""
@author: Wu Liang
@authors: 
@date: Jun 4, 2012 8:24:36 PM
@contact: wuliang@maimiaotech.com
@version: 0.0.0
@deprecated:
@license:
@copyright:
"""

from Sku import Sku
from StaffEvalStatById import StaffEvalStatById
from VideoItem import VideoItem
from FavoriteItem import FavoriteItem
from ReplyStatOnDay import ReplyStatOnDay
from Demographic import Demographic
from TOPPaginator import TOPPaginator
from ProductSpec import ProductSpec
from LimitDiscountDetail import LimitDiscountDetail
from AddressResult import AddressResult
from Department import Department
from INWordCategory import INWordCategory
from ADGroupCatMatchPage import ADGroupCatMatchPage
from TmcUser import TmcUser
from Brand import Brand
from ProductImg import ProductImg
from CampaignSchedule import CampaignSchedule
from INWordAnalysis import INWordAnalysis
from LoginLog import LoginLog
from PromotionInShop import PromotionInShop
from Duty import Duty
from ArticleSub import ArticleSub
from Task import Task
from Keyword import Keyword
from SubUserPermission import SubUserPermission
from PromotionRange import PromotionRange
from IdsModule import IdsModule
from Shipping import Shipping
from SuiteConfDO import SuiteConfDO
from CreativeRecord import CreativeRecord
from FoodSecurity import FoodSecurity
from Shop import Shop
from ADGroupCatmatch import ADGroupCatmatch
from Campaign import Campaign
from RefundBaseResponse import RefundBaseResponse
from Qscore import Qscore
from ProductBooks import ProductBooks
from VideoPlayInfo import VideoPlayInfo
from PaimaiInfo import PaimaiInfo
from TransitStepInfo import TransitStepInfo
from Role import Role
from AccountStat import AccountStat
from ModularDescInfo import ModularDescInfo
from CatBrandSaleProp import CatBrandSaleProp
from Area import Area
from CarriageDetail import CarriageDetail
from StreamWeight import StreamWeight
from ItemProp import ItemProp
from INWordBase import INWordBase
from UserCredit import UserCredit
from Location import Location
from OnlineTimeById import OnlineTimeById
from PropImg import PropImg
from Picture import Picture
from AndroidVlowUrl import AndroidVlowUrl
from ADGroup import ADGroup
from DeliveryTemplate import DeliveryTemplate
from Permission import Permission
from ProductPropImg import ProductPropImg
from KfcSearchResult import KfcSearchResult
from SubUserFullInfo import SubUserFullInfo
from GroupMember import GroupMember
from AreaOption import AreaOption
from TicketItemProcessResult import TicketItemProcessResult
from INCategoryAnalysis import INCategoryAnalysis
from CampaignArea import CampaignArea
from RefundRemindTimeout import RefundRemindTimeout
from DataPushTask import DataPushTask
from RankedItem import RankedItem
from INCategoryBase import INCategoryBase
from SellerCat import SellerCat
from BrandCatControlInfo import BrandCatControlInfo
from ItemPromotion import ItemPromotion
from ItemTemplate import ItemTemplate
from Place import Place
from LogisticsCompany import LogisticsCompany
from AfterSale import AfterSale
from CertTxtInfo import CertTxtInfo
from RecommendWord import RecommendWord
from KeywordPage import KeywordPage
from PropertyInputDO import PropertyInputDO
from SubUserInfo import SubUserInfo
from Trade import Trade
from KeywordQscore import KeywordQscore
from UserSubscribe import UserSubscribe
from UserInfo import UserInfo
from RdsConfig import RdsConfig
from OrderAmount import OrderAmount
from ReplyStatById import ReplyStatById
from WaitingTimesOnDay import WaitingTimesOnDay
from INCategoryChildTop import INCategoryChildTop
from DeliveryTime import DeliveryTime
from Promotion import Promotion
from SpuTemplateDO import SpuTemplateDO
from Activity import Activity
from ItemDescModule import ItemDescModule
from Creative import Creative
from Privilege import Privilege
from TmcGroup import TmcGroup
from Evaluation import Evaluation
from ArticleUserSubscribe import ArticleUserSubscribe
from TicketEtc import TicketEtc
from ArticleBizOrder import ArticleBizOrder
from ADGroupPlace import ADGroupPlace
from TicketItem import TicketItem
from FavoriteShop import FavoriteShop
from ADGroupPage import ADGroupPage
from ExtraAttributes import ExtraAttributes
from StaffEvalStatOnDay import StaffEvalStatOnDay
from Subtask import Subtask
from INCategoryTop import INCategoryTop
from TopFee import TopFee
from ShopCat import ShopCat
from DemographicSetting import DemographicSetting
from OnlineTimesOnDay import OnlineTimesOnDay
from TradeRate import TradeRate
from User import User
from TradeAmount import TradeAmount
from KeywordForecast import KeywordForecast
from CampaignPlatform import CampaignPlatform
from PromotionInItem import PromotionInItem
from LimitDiscount import LimitDiscount
from SubAccountInfo import SubAccountInfo
from Feature import Feature
from ADGroupCatMatchForecast import ADGroupCatMatchForecast
from EvalDetail import EvalDetail
from PromotionTag import PromotionTag
from INCategoryProperties import INCategoryProperties
from LogisticServiceTag import LogisticServiceTag
from PromotionMjs import PromotionMjs
from BrandCatControl import BrandCatControl
from Refund import Refund
from Coupon import Coupon
from SubwayItem import SubwayItem
from SellerAuthorize import SellerAuthorize
from CreativePage import CreativePage
from PromotionDisplayTop import PromotionDisplayTop
from Video import Video
from PicUrl import PicUrl
from PartnerDetail import PartnerDetail
from ProductExtraInfo import ProductExtraInfo
from RecommendWordPage import RecommendWordPage
from LogisticsPartner import LogisticsPartner
from ItemCat import ItemCat
from ItemImg import ItemImg
from TOPSearchResult import TOPSearchResult
from MjsPromotion import MjsPromotion
from RefundMessage import RefundMessage
from ChannelOption import ChannelOption
from PictureCategory import PictureCategory
from Product import Product
from CertPicInfo import CertPicInfo
from WaitingTimeById import WaitingTimeById
from PromotionDetail import PromotionDetail
from Ticket import Ticket
from ServiceOrder import ServiceOrder
from MpicVideo import MpicVideo
from LocalityLife import LocalityLife
from NonreplyStatById import NonreplyStatById
from PromotionTagQuery import PromotionTagQuery
from JdpUser import JdpUser
from Item import Item
from PropValue import PropValue
from CampaignBudget import CampaignBudget
from Meal import Meal
from Order import Order
from NonReplyStatOnDay import NonReplyStatOnDay
from ScoreResult import ScoreResult
from INRecordBase import INRecordBase
from TmcMessage import TmcMessage
from QueryRow import QueryRow
from ShopScore import ShopScore
from TradeConfirmFee import TradeConfirmFee
from LogisticsTag import LogisticsTag
from SubwayItemPartition import SubwayItemPartition
from DescModuleInfo import DescModuleInfo
